'use client'
import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Staatliches } from 'next/font/google'
const font = Staatliches({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'SPEEDCUBING TOOLKIT',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <div id='root'>

          <Navbar />

          <main style={{ display: 'flex', width: '100%', height: '100%' }}>

            {children}

          </main>

        </div>
      </body>
    </html>
  )
}
