'use client'
import Navbar from '../components/Navbar/Navbar'
import './globals.css'
import { Staatliches } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import { CacheProvider } from '@chakra-ui/next-js'

export const metadata = {
  title: 'SPEEDCUBING TOOLKIT',
  description: 'Generated by create next app'
}
const font = Staatliches({ subsets: ['latin'], weight: '400' })

export default function RootLayout ({ children }) {
  return (

    <html lang='en'>
      <body className={font.className}>
        <CacheProvider>
          <ChakraProvider>
            <Navbar />
            <main style={{ display: 'flex', width: '100%', height: '100%' }}>
              {children}
            </main>
          </ChakraProvider>
        </CacheProvider>

      </body>
    </html>
  )
}
