'use client'
import Navbar from '../components/Navbar/Navbar'
import './globals.css'
import { Staatliches } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import { CacheProvider } from '@chakra-ui/next-js'
// import { AppContext } from '@/context/AppContext'
// import {
//   onAuthStateChanged,
//   getAuth
// } from 'firebase/auth'
// import firebaseApp from '@/firebase/config'

// const auth = getAuth(firebaseApp)

export const metadata = {
  title: 'SPEEDCUBING TOOLKIT',
  description: 'Generated by create next app'
}
const font = Staatliches({ subsets: ['latin'], weight: '400' })

export default function RootLayout ({ children }) {
  // const [user, setUser] = useState(null)

  // useEffect(() => {
  //   const unsubscribe = onAuthStateChanged(auth, (user) => {
  //     if (user) {
  //       setUser(user)
  //     } else {
  //       setUser(null)
  //     }
  //   })

  //   return () => unsubscribe()
  // }, [])

  return (
    <html lang='en'>
      <body className={font.className}>
        <CacheProvider>
          <ChakraProvider>
            <Navbar />
            <main style={{ display: 'flex', width: '100%', height: '100%' }}>
              {children}
            </main>
          </ChakraProvider>
        </CacheProvider>

      </body>
    </html>
  )
}
